title: BigStone Wiki
description: A comprehensive guide to Bigstone, covering its features, usage, and best practices.
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
